import { SOURCE_REFRESH_SECONDS } from '../shared/cachePolicy.js'

export const WEATHER_FRESH_CACHE_TTL = SOURCE_REFRESH_SECONDS
export const AIR_QUALITY_FRESH_CACHE_TTL = SOURCE_REFRESH_SECONDS
export const STALE_CACHE_TTL = 24 * 60 * 60
